# Generated by Django 4.2.7 on 2023-11-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='tenant',
            field=models.CharField(choices=[('Offen', 'Offen'), ('Vergeben', 'Vergeben'), ('In Arbeit', 'In Arbeit'), ('Komplett', 'Komplett'), ('Abgebrochen', 'Abgebrochen')], default='Offen', max_length=15),
        ),
    ]
